# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import logging
import os
from pathlib import Path
import shutil
import subprocess
import sys
from urllib.parse import urlsplit, urlunsplit
import warnings
import yaml

import matplotlib

from datetime import datetime
import time
import sphinx_rtd_theme

sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.abspath(os.path.pardir))
sys.path.insert(0, os.path.abspath("../../../"))

warnings.filterwarnings("error", append=True)

# -- Project information -----------------------------------------------------

project = "brainvistools"
copyright = "2022, Leon Martin, Petra Ritter"
author = "Leon Martin"

# The full version, including alpha/beta/rc tags


import brainvistools

version = brainvistools.__version__
release = brainvistools.__version__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.duration",
    "sphinx.ext.doctest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx_rtd_theme",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_gallery.gen_gallery",
    "matplotlib.sphinxext.mathmpl",
    "matplotlib.sphinxext.plot_directive",
    "nbsphinx",
]

# Generate the API documentation when building
autosummary_generate = True
warnings.filterwarnings(
    "ignore",
    category=DeprecationWarning,
    module="importlib",  # used by sphinx.autodoc.importer
    message=r"(\n|.)*module was deprecated.*",
)

autodoc_default_options = {"members": True, "inherited-members": True}
numpydoc_show_class_members = False
autoclass_content = "class"

# make sure to ignore warnings that stem from simply inspecting deprecated
# class-level attributes
warnings.filterwarnings(
    "ignore", category=DeprecationWarning, module="sphinx.util.inspect"
)


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
import sphinx_rtd_theme  # noqa

html_theme = "sphinx_rtd_theme"
html_show_sourcelink = False

html_theme = "sphinx_rtd_theme"
html_logo = "../../images/logo.png"
html_theme_options = {"logo_only": True}


# CSS files to include
html_css_files = ["theme_overrides.css"]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "brainvistoolsdoc"

# -- Options for Latex output ---------------------------------------------

latex_engine = "lualatex"
latex_elements = {
    "fontpkg": r"""
    \setmainfont{Arial}
""",
    "preamble": r"""
    \usepackage{unicode-math}""",
}


# -- Extension configuration -------------------------------------------------
intersphinx_mapping = {
    "python": ("https://docs.python.org/3.6", None),
    "matplotlib": ("https://matplotlib.org", None),
    "numpy": ("https://docs.scipy.org/doc/numpy", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    "bids": ("https://bids-standard.github.io/pybids/", None),
    "nibabel": ("https://nipy.org/nibabel/", None),
    "nilearn": ("https://nilearn.github.io/stable/", None),
    "nipype": ("https://nipype.readthedocs.io/en/latest/", None),
    "niworkflows": ("https://www.nipreps.org/niworkflows/", None),
    "sdcflows": ("https://www.nipreps.org/sdcflows/", None),
    "smriprep": ("https://www.nipreps.org/smriprep/", None),
    "templateflow": ("https://www.templateflow.org/python-client", None),
}

sphinx_gallery_conf = {
    "doc_module": "brainvistools",
    "examples_dirs": "../../examples",
    "gallery_dirs": "auto_examples",
    "backreferences_dir": os.path.join("generated", "modules"),
    "reference_url": {"brainvistools": None},
    "thumbnail_size": (250, 250),
    "compress_images": ("thumbnails", "images"),
    "plot_gallery": "True",  # sphinx-gallery/913
    "ignore_pattern": r"/wip.*\.py",
}
